### ISSUE TITLE
Problem regarding links

### ISSUE THREAD

**Issue by PRGfx** [tomvlk/MPFormatter_android#1]
As far as I can judge by trying, the last character in - at least $l|h[...] - links is cut off.

`$l[somelink]sometext$l`=> `<a href="somelin">sometext</a>`

**Comment by tomvlk** [comment]
This is a bug in the current version, Fix will be released asap...

**Comment by tomvlk** [comment]
Should be updated in 1.2, if you change the gradle compile version in your dependencies (or redownload if not using gradle) it should be alright.
Thanks
